// Code generated by `autotier bench import`. DO NOT EDIT.
// Evidencia auditada de benchmarks publicos; ver internal/bench/data/.
package catalog

// generatedScores sobreescribe priors curados con blend evidencia+prior.
var generatedScores = map[string]Scores{
	"balanced-tier": {"code": 8, "reasoning": 8},
	"frontier-tier": {"code": 9, "reasoning": 9},
	"haiku-tier":    {"code": 7, "reasoning": 6},
}

// generatedProvenance documenta fuente y fecha por celda aplicada.
var generatedProvenance = map[string]string{
	"balanced-tier|code":      "gpqa-diamond@2026-09-09, swe-bench-verified@2026-09-09",
	"balanced-tier|reasoning": "gpqa-diamond@2026-09-09, swe-bench-verified@2026-09-09",
	"frontier-tier|code":      "gpqa-diamond@2026-09-09, swe-bench-verified@2026-09-09",
	"frontier-tier|reasoning": "gpqa-diamond@2026-09-09, swe-bench-verified@2026-09-09",
	"haiku-tier|code":         "gpqa-diamond@2026-09-09, swe-bench-verified@2026-09-09",
	"haiku-tier|reasoning":    "gpqa-diamond@2026-09-09, swe-bench-verified@2026-09-09",
}
